[package]
name = "mxboot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
thiserror = "1.0.38"
syscalls = { version = "0.6.7", features = ["aarch64"], default-features = false }
embedded-graphics = "0.7.1"
framebuffer = "0.3.1"
lvgl = "0.5.2"
